# -*- coding: utf-8 -*-
"""ASSIGNMENT 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-be_7iQToaeh78e5tEwyBVtDPb3DLrR

Q1. Class Marks Report
"""

marks = [78, 45, 92, 33, 67, 88, 51, 29]

print("Highest mark:", max(marks))
print("Lowest mark:", min(marks))

avg = sum(marks) / len(marks)
print("Class average:",avg)

passed = 0
for m in marks:
    if m >= 35:
        passed += 1
print("Students passed:", passed)

"""Q2. Grocery Shopping List"""

shopping = []

while True:
    item = input("Enter item: ")
    if item == "done":
        break
    if item in shopping:
        print("Already added")
    else:
        shopping.append(item)

for num, item in enumerate(shopping, start=1):
    print(f"{num}. {item}")

print("Total items:", len(shopping))

"""Q3. Username Validator"""

name = input("Enter username: ")

if len(name) < 5 or len(name) > 12:
    print("Invalid: Username must be between 5 and 12 characters")
elif " " in name:
    print("Invalid: Username cannot contain spaces")
elif name[0].isdigit():
    print("Invalid: Username cannot start with a digit")
else:
    print("Valid username")

"""Q4. Vowel Counter for a Tweet"""

text = input("Enter a sentence: ")

vowels = 0
consonants = 0
spaces = 0

for ch in text:
    if " " in ch:                     # is it a space?
        spaces += 1
    elif ch.isalpha()  :                    # is it a letter?
        if ch.lower() in "aeiou":                  # is it a vowel? (use lower())
            vowels += 1
        else:
            consonants += 1

print("Vowels:", vowels)
print("Consonants:", consonants)
print("Spaces:", spaces)

"""Q5. Palindrome Name Checker"""

name = input("Enter your name: ")

cleaned = name.lower()

if cleaned == cleaned[::-1]:
    print("Bonus! Your name is a palindrome.")
else:
    print("Not a palindrome. No bonus this time.")

"""Q6. Temperature Tracker"""

temps = [32, 35, 38, 41, 36, 29, 40]
days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

# Days above 37
print("Heat alert days:")
for i in range(len(temps)):
    if temps[i] > 37:
        print(days[i], "-", temps[i])

# Hottest day
hottest = max(temps)
position = temps.index(hottest)
print("Hottest day:", days[position], "with", hottest)

# Convert to Fahrenheit
fahrenheit = []
for t in temps:
    fahrenheit.append(t * 9 / 5 + 32)
print("Temperatures in Fahrenheit:", fahrenheit)

"""Q7. Word Frequency in a Sentence"""

sentence = input("Enter a sentence: ")
words = sentence.split()        # split into list of words

longest = words[0]
shortest = words[0]
capital_count = 0

for word in words:
    if len(word) > len(longest):
        longest = word
    if len(word) < len(shortest):
        shortest = word
    if word[0].isupper():
        capital_count = capital_count + 1

print("Longest word:", longest)
print("Shortest word:", shortest)
print("Words starting with capital letter:", capital_count)

"""Q8. Remove Negative Balances"""

balances = [1500, -200, 3000, -50, 0, 750, -1000]

positive_accounts = []
negative_accounts = []
total_owed = 0

for b in balances:
    if b > 0:
        positive_accounts.append(b)
    elif b < 0:
        negative_accounts.append(b)
        total_owed = total_owed + abs(b)    # abs() removes minus sign

print("Positive accounts:", positive_accounts)
print("Negative accounts:", negative_accounts)
print("Total amount owed:", total_owed)

"""Q9. Password Strength Checker"""

password = input("Enter password: ")

has_upper = False
has_lower = False
has_digit = False

for ch in password:
    if ch.isupper():
        has_upper = True
    elif ch.islower():
        has_lower = True
    elif ch.isdigit():
        has_digit = True

# Count how many conditions are met
score = 0
if has_upper:
    score = score + 1
if has_lower:
    score = score + 1
if has_digit:
    score = score + 1
if len(password) >= 8:
    score = score + 1

if score == 4:
    print("Strong")
elif score == 2 or score == 3:
    print("Medium")
else:
    print("Weak")

"""Q10. Simple Name Initials Generator"""

full_name = input("Enter full name: ")
parts = full_name.split()       # list of words in the name

# 1) Initials with dots -> R.K.S.
initials = ""
for p in parts:
    initials = initials + p[0].upper() + "."
print("Initials:", initials)

# 2) Title case -> Ruchik Kumar Sharma
print("Title case:", full_name.title())

# 3) Surname in full -> R. K. Sharma
short_name = ""
for p in parts[:-1]:            # all words except the last one
    short_name = short_name + p[0].upper() + ". "
short_name = short_name + parts[-1].title()
print("With surname:", short_name)