# -*- coding: utf-8 -*-
"""Assignment_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dpeSY7byzcz5IxSj7h0ePAePdZlmXpmF

Q1. Phone Contact Book
"""

contacts = {}       # empty dictionary: name -> phone number

while True:
    print("\n1. Add contact")
    print("2. Search contact")
    print("3. Show all contacts")
    print("4. Exit")
    choice = input("Enter your choice: ")

    if choice == "1":
        name = input("Enter name: ")
        if name in contacts:                # name already a key
            print("Contact already exists")
        else:
            phone = input("Enter phone number: ")
            contacts[name] = phone          # add new key-value pair
            print("Contact added")

    elif choice == "2":
        name = input("Enter name to search: ")
        if name in contacts:
            print(name, ":", contacts[name])
        else:
            print("Contact not found")

    elif choice == "3":
        if len(contacts) == 0:
            print("No contacts yet")
        else:
            for name, phone in contacts.items():    # items() gives key and value
                print(name, ":", phone)

    elif choice == "4":
        print("Bye!")
        break                               # leave the menu loop

    else:
        print("Invalid choice")

"""Q2. Unique Visitors on a Website"""

visits = [101, 205, 101, 330, 205, 412, 101, 330, 509]

unique_visitors = set(visits)       # a set removes duplicates automatically

print("Total visits:", len(visits))
print("Unique visitors:", len(unique_visitors))
print("Unique visitor IDs:", sorted(unique_visitors))   # sorted() gives a list

"""Q3. Student Marks Dictionary"""

marks = {"Aman": 82, "Priya": 91, "Rahul": 45, "Sneha": 67, "Kiran": 30}

# Pass or Fail for each student (pass mark is 40)
for name, mark in marks.items():
    if mark >= 40:
        print(name, "- Pass")
    else:
        print(name, "- Fail")

# Find the topper
topper = ""
top_marks = 0
for name, mark in marks.items():
    if mark > top_marks:
        top_marks = mark
        topper = name
print("Topper:", topper, "with", top_marks, "marks")

# New dictionary with only passed students
passed_students = {}
for name, mark in marks.items():
    if mark >= 40:
        passed_students[name] = mark
print("Passed students:", passed_students)

"""Q4. Common Friends"""

riya_friends = {"Aman", "Neha", "Karan", "Sita", "Vikram"}
arjun_friends = {"Neha", "Vikram", "Pooja", "Aman", "Rohan"}

# intersection: present in both sets
print("Mutual friends:", sorted(riya_friends.intersection(arjun_friends)))

# difference: in Riya's set but not in Arjun's
print("Only Riya has:", sorted(riya_friends.difference(arjun_friends)))

# union: everyone, without duplicates
print("All people:", sorted(riya_friends.union(arjun_friends)))

# Arjun's friends that Riya does not know
print("Suggestions for Riya:", sorted(arjun_friends.difference(riya_friends)))

"""Q5. Character Counter"""

text = input("Enter text: ")

count = {}      # character -> how many times it appears

for ch in text:
    if ch != " ":                           # ignore spaces
        count[ch] = count.get(ch, 0) + 1    # get() returns 0 if ch is new
print(count)

# Find the most frequent character
best_char = ""
best_count = 0
for ch, c in count.items():
    if c > best_count:
        best_count = c
        best_char = ch
print("Most frequent character:", best_char, "(" + str(best_count), "times)")

"""Q6. Restaurant Menu Billing"""

menu = {"dosa": 60, "idli": 40, "vada": 30, "coffee": 25, "tea": 15}
total = 0

while True:
    order = input("What would you like to order (type bill to finish)? ")
    if order == "bill":
        break
    elif order in menu:
        total = total + menu[order]         # add the price
        print(order, "added. Price:", menu[order])
    else:
        print("Item not available")

print("Total:", total)

# 10% discount if total is more than Rs. 200
if total > 200:
    discount = total * 10 / 100
    total = total - discount
    print("Discount (10%):", discount)

print("Final bill: Rs.", total)

"""Q7. City Coordinates (Tuples)"""

cities = [("Hyderabad", 17.38, 78.48),
          ("Mumbai", 19.07, 72.87),
          ("Chennai", 13.08, 80.27),
          ("Delhi", 28.61, 77.20)]

# Unpack each tuple into three variables in the for loop
for city, lat, lon in cities:
    print(city, "- Latitude:", lat, "Longitude:", lon)

# Farthest north = highest latitude
north_city = ""
north_lat = 0
for city, lat, lon in cities:
    if lat > north_lat:
        north_lat = lat
        north_city = city
print("Farthest north:", north_city, "(", north_lat, ")")

# Trying to change a value inside a tuple:
# cities[1][1] = 20.00
#
# Error: TypeError: 'tuple' object does not support item assignment
# Reason: Tuples are immutable, which means their values cannot be
# changed after the tuple is created. (Lists can be changed, tuples cannot.)

"""Q8. Library Book Tracker"""

books = {"Python Basics": 3, "Data Science 101": 0,
         "Machine Learning": 2, "SQL Guide": 1}

book = input("Enter book name to borrow: ")

if book not in books:
    print("Book not found")
elif books[book] == 0:
    print("Currently unavailable")
else:
    books[book] = books[book] - 1           # one copy is issued
    print("Book issued successfully")

print("Updated books:", books)

"""Q9. Group Employees by Department"""

employees = [("Ravi", "IT"), ("Anjali", "HR"), ("Suresh", "IT"),
             ("Meena", "Finance"), ("Arun", "HR"), ("Divya", "IT")]

departments = {}

for name, dept in employees:
    if dept not in departments:
        departments[dept] = []              # new department: empty list
    departments[dept].append(name)          # add employee to that list

print(departments)

# Number of employees in each department
for dept, names in departments.items():
    print(dept, ":", len(names), "employees")

"""Q10. Quiz Answer Checker"""

answer_key = ("B", "C", "A", "D", "B")
wrong_questions = set()         # set to store wrong question numbers
score = 0

for i in range(5):
    ans = input("Enter answer for question " + str(i + 1) + ": ").upper()
    if ans == answer_key[i]:
        print("Question", i + 1, "- Correct")
        score = score + 1
    else:
        print("Question", i + 1, "- Wrong")
        wrong_questions.add(i + 1)

print("Wrong questions:", wrong_questions)
print("Score:", score, "/ 5")

if score == 5:
    print("Remark: Excellent")
elif score >= 3:
    print("Remark: Good")
else:
    print("Remark: Needs improvement")