# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oN-VE54nPlG57yY0wNm1HTV0N5VESBTI

Q1. Movie Ticket Counter
"""

age = int(input("Enter your age:"))
if age < 5:
    print("you are free")
elif age <= 17:
    print("Your ticket price is Rs. 100")
elif age <= 59:
    print("Your ticket price is Rs. 200")
else:
    print("Your ticket price is Rs. 120")

"""Q2. Electricity Bill Calculator"""

units = int(input("enter the unit please:"))
if units <=100:
  bill = units * 3
  print("Total bill: Rs." + str(bill))
  print(f"({units}*3 = {bill})")
elif units <= 200:
  extra = units - 100
  bill = 100 * 3  + extra * 5
  print(f"Total bill: Rs. {bill}")
  print(f"(100*3 + {extra}*5 = {100*3} + {extra*5})")

else:#250
  extra = units - 200
  bill = 100 * 3 +100 *5  + extra*8
  print(f"Total bill: Rs. {bill}")
  print(f"(100*3 + 100*5 + {extra}*8 = {100*3} + {100*5} + {extra*8})")

"""Q3. Multiplication Table for a Kid"""

number = int(input("Enter a number:"))
for i in range(1, 11):
    print(f"{number} x {i} = {number * i}")

"""Q4. Savings Piggy Bank"""

total = 0
days = 0
while total < 1000:
    money = int(input("Enter today's savings: "))
    total += money
    days += 1
print(f"Goal reached in {days} days! Total saved: Rs. {total}")

"""Q5. ATM PIN Check"""

i = 1
granted = False          # nobody has been let in yet

while i < 4:
    pin = int(input("Enter the Pin :"))
    if pin == 4321:
        print("Access granted")
        granted = True   # remember that it worked
        break
    else:
        print("Wrong PIN")
    i += 1

if not granted:          # only block if the PIN was never correct
    print("Card blocked")

"""Q6. Even and Odd Counter"""

even = 0
odd = 0
number = int(input("enter the number"))
for i in range(1,number+1):
  if (i % 2 == 0):
    even += 1
  else:
    odd +=1
  i+=1
print ( "Even numbers:" ,even)
print("odd numbers:",odd)

"""Q7. Number Guessing Game"""

secret_number = 27
i = 0
move = 0
while i <= 15:
  number = int(input("Guess the number:"))
  if number > secret_number:
    print("Too high")
    move += 1
  elif ( number == secret_number):
    move +=1
    break
  else:
    print("Too low")
    move +=1
  i +=1
print(f"Correct! You took {move} guesses.")

"""Q8. Exam Result with Grade"""

marks = int(input("Enter marks: "))

if marks < 0 or marks > 100:
    print("Invalid marks")
elif marks >= 90:
    print("A")
elif marks >= 75:
    print("B")
elif marks >= 50:
    print("C")
elif marks >= 35:
    print("D")
else:
    print("Fail")

"""Q9. Sum of Digits on a Bill Number"""

bill = int(input("Enter bill number: "))

total = 0
n = bill

while n > 0:
    digit = n % 10      # last digit
    total += digit      # add it to the sum
    n = n // 10         # remove the last digit

print("Sum of digits:", total)

if total > 20:
    print("Congratulations! You win a free gift.")
else:
    print("Sorry, no gift this time.")

"""Q10. Staircase Pattern"""

steps = int(input("Enter number of steps: "))

for i in range(1, steps + 1):
    for j in range(i):
        print("*", end=" ")
    print()